import Head from 'next/head'
import { Inter } from '@next/font/google'
import { ProjectCard } from '@/components/ProjectCard'
import { Hero } from '@/components/Hero'
import { SectionTitle } from '@/components/SectionTitle'
import { Work } from '@/components/Work'
import { Header } from '@/components/Header'
import { useState } from 'react'
import { PageLink } from '@/components/Link'
import { ClassesContainer } from '@/components/ClassesContainer'
import { AnimationOnScroll } from 'react-animation-on-scroll'
import Image from 'next/image'
import aboutImage from "public/undraw_drink_coffee_jdqb.svg"
import { About } from '@/components/About'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);


  return (
    <>
      <Head>
        <title>Scott Kenning</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Coming+Soon&family=Lato:wght@400;700&display=swap" rel="stylesheet"/>
      </Head>
      <main className="overflow-y-auto flex flex-col items-center w-100 font-Lato text-white text-lg bg-auto bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-[#23486F] via-[#192532] to-[#10131C]">
        <div className='flex flex-col items-center md:w-8/12 w-11/12'>

          <Hero/>  

          <AnimationOnScroll animateIn="animate__fadeIn" animateOnce={true} className='mb-96'>
            <SectionTitle title="About Me"/>
            <About/>
          </AnimationOnScroll>

          <AnimationOnScroll animateIn="animate__fadeIn" animateOnce={true} className='mb-96'>
            <SectionTitle title="Featured Project"/>
            <div className="flex flex-col items-center">
              <ProjectCard/>
            </div>
          </AnimationOnScroll>

          <AnimationOnScroll animateIn="animate__fadeIn" animateOnce={true}>
          <div className='flex flex-col w-full px-4 mt-16'>
            <SectionTitle title="Work Experience"/>
            <Work/>
          </div>
          </AnimationOnScroll>

        </div>
      </main>
    </>
  )
}
